import { default as Input } from '@mui/joy/Input'
import { NotImplemented, ModelConfig } from '@/components/ModelRuntimeConfig'
import { ApplicantModel } from '@/schemas/index.ts'

export const applicantModelConfig: ModelConfig<ApplicantModel> = {
  _links: {
    key: '_links',
    label: '_links',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  _embedded: {
    key: '_embedded',
    label: '_embedded',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  id: {
    key: 'id',
    label: 'id',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  created: {
    key: 'created',
    label: 'created',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  modified: {
    key: 'modified',
    label: 'modified',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  marketingMode: {
    key: 'marketingMode',
    label: 'marketingMode',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  currency: {
    key: 'currency',
    label: 'currency',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  active: {
    key: 'active',
    label: 'active',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  notes: {
    key: 'notes',
    label: 'notes',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  sellingStatus: {
    key: 'sellingStatus',
    label: 'sellingStatus',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  sellingPosition: {
    key: 'sellingPosition',
    label: 'sellingPosition',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  statusId: {
    key: 'statusId',
    label: 'statusId',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  lastCall: {
    key: 'lastCall',
    label: 'lastCall',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  nextCall: {
    key: 'nextCall',
    label: 'nextCall',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  departmentId: {
    key: 'departmentId',
    label: 'departmentId',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  solicitorId: {
    key: 'solicitorId',
    label: 'solicitorId',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  potentialClient: {
    key: 'potentialClient',
    label: 'potentialClient',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  type: {
    key: 'type',
    label: 'type',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  style: {
    key: 'style',
    label: 'style',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  situation: {
    key: 'situation',
    label: 'situation',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  parking: {
    key: 'parking',
    label: 'parking',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  age: {
    key: 'age',
    label: 'age',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  locality: {
    key: 'locality',
    label: 'locality',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  specialFeatures: {
    key: 'specialFeatures',
    label: 'specialFeatures',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  unmappedRequirements: {
    key: 'unmappedRequirements',
    label: 'unmappedRequirements',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  bedroomsMin: {
    key: 'bedroomsMin',
    label: 'bedroomsMin',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  bedroomsMax: {
    key: 'bedroomsMax',
    label: 'bedroomsMax',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  receptionsMin: {
    key: 'receptionsMin',
    label: 'receptionsMin',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  receptionsMax: {
    key: 'receptionsMax',
    label: 'receptionsMax',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  bathroomsMin: {
    key: 'bathroomsMin',
    label: 'bathroomsMin',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  bathroomsMax: {
    key: 'bathroomsMax',
    label: 'bathroomsMax',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  parkingSpacesMin: {
    key: 'parkingSpacesMin',
    label: 'parkingSpacesMin',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  parkingSpacesMax: {
    key: 'parkingSpacesMax',
    label: 'parkingSpacesMax',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  locationType: {
    key: 'locationType',
    label: 'locationType',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  locationOptions: {
    key: 'locationOptions',
    label: 'locationOptions',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  archivedOn: {
    key: 'archivedOn',
    label: 'archivedOn',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  fromArchive: {
    key: 'fromArchive',
    label: 'fromArchive',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  buying: {
    key: 'buying',
    label: 'buying',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  renting: {
    key: 'renting',
    label: 'renting',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  externalArea: {
    key: 'externalArea',
    label: 'externalArea',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  internalArea: {
    key: 'internalArea',
    label: 'internalArea',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  source: {
    key: 'source',
    label: 'source',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  commercial: {
    key: 'commercial',
    label: 'commercial',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  regional: {
    key: 'regional',
    label: 'regional',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  officeIds: {
    key: 'officeIds',
    label: 'officeIds',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  negotiatorIds: {
    key: 'negotiatorIds',
    label: 'negotiatorIds',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  related: {
    key: 'related',
    label: 'related',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  metadata: {
    key: 'metadata',
    label: 'metadata',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  _eTag: {
    key: '_eTag',
    label: '_eTag',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
}
