import { default as Input } from '@mui/joy/Input'
import { NotImplemented, ModelConfig } from '@/components/ModelRuntimeConfig'
import { CompanyModel } from '@/schemas/index.ts'

export const companyModelConfig: ModelConfig<CompanyModel> = {
  _links: {
    key: '_links',
    label: '_links',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  _embedded: {
    key: '_embedded',
    label: '_embedded',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  id: {
    key: 'id',
    label: 'id',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  created: {
    key: 'created',
    label: 'created',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  modified: {
    key: 'modified',
    label: 'modified',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  name: {
    key: 'name',
    label: 'name',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  branch: {
    key: 'branch',
    label: 'branch',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  notes: {
    key: 'notes',
    label: 'notes',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  active: {
    key: 'active',
    label: 'active',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  marketingConsent: {
    key: 'marketingConsent',
    label: 'marketingConsent',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  vatRegistered: {
    key: 'vatRegistered',
    label: 'vatRegistered',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  typeIds: {
    key: 'typeIds',
    label: 'typeIds',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  supplierTypeId: {
    key: 'supplierTypeId',
    label: 'supplierTypeId',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  workPhone: {
    key: 'workPhone',
    label: 'workPhone',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  mobilePhone: {
    key: 'mobilePhone',
    label: 'mobilePhone',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  email: {
    key: 'email',
    label: 'email',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  archivedOn: {
    key: 'archivedOn',
    label: 'archivedOn',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  fromArchive: {
    key: 'fromArchive',
    label: 'fromArchive',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  address: {
    key: 'address',
    label: 'address',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  payments: {
    key: 'payments',
    label: 'payments',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  additionalContactDetails: {
    key: 'additionalContactDetails',
    label: 'additionalContactDetails',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  officeIds: {
    key: 'officeIds',
    label: 'officeIds',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  negotiatorIds: {
    key: 'negotiatorIds',
    label: 'negotiatorIds',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  communicationPreferenceLetter: {
    key: 'communicationPreferenceLetter',
    label: 'communicationPreferenceLetter',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  communicationPreferenceEmail: {
    key: 'communicationPreferenceEmail',
    label: 'communicationPreferenceEmail',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  communicationPreferencePhone: {
    key: 'communicationPreferencePhone',
    label: 'communicationPreferencePhone',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  communicationPreferenceSms: {
    key: 'communicationPreferenceSms',
    label: 'communicationPreferenceSms',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  metadata: {
    key: 'metadata',
    label: 'metadata',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  _eTag: {
    key: '_eTag',
    label: '_eTag',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  relationships: {
    key: 'relationships',
    label: 'relationships',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
}
