import { default as Input } from '@mui/joy/Input'
import { NotImplemented, ModelConfig } from '@/components/ModelRuntimeConfig'
import { ContactModel } from '@/schemas/index.ts'

export const contactModelConfig: ModelConfig<ContactModel> = {
  _links: {
    key: '_links',
    label: '_links',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  _embedded: {
    key: '_embedded',
    label: '_embedded',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  id: {
    key: 'id',
    label: 'id',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  created: {
    key: 'created',
    label: 'created',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  modified: {
    key: 'modified',
    label: 'modified',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  title: {
    key: 'title',
    label: 'title',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  forename: {
    key: 'forename',
    label: 'forename',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  surname: {
    key: 'surname',
    label: 'surname',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  dateOfBirth: {
    key: 'dateOfBirth',
    label: 'dateOfBirth',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  active: {
    key: 'active',
    label: 'active',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  marketingConsent: {
    key: 'marketingConsent',
    label: 'marketingConsent',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  identityCheck: {
    key: 'identityCheck',
    label: 'identityCheck',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  source: {
    key: 'source',
    label: 'source',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  homePhone: {
    key: 'homePhone',
    label: 'homePhone',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  workPhone: {
    key: 'workPhone',
    label: 'workPhone',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  mobilePhone: {
    key: 'mobilePhone',
    label: 'mobilePhone',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  email: {
    key: 'email',
    label: 'email',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  archivedOn: {
    key: 'archivedOn',
    label: 'archivedOn',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  fromArchive: {
    key: 'fromArchive',
    label: 'fromArchive',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  primaryAddress: {
    key: 'primaryAddress',
    label: 'primaryAddress',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  secondaryAddress: {
    key: 'secondaryAddress',
    label: 'secondaryAddress',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  workAddress: {
    key: 'workAddress',
    label: 'workAddress',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  officeIds: {
    key: 'officeIds',
    label: 'officeIds',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  negotiatorIds: {
    key: 'negotiatorIds',
    label: 'negotiatorIds',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  categoryIds: {
    key: 'categoryIds',
    label: 'categoryIds',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  communicationPreferenceLetter: {
    key: 'communicationPreferenceLetter',
    label: 'communicationPreferenceLetter',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  communicationPreferenceEmail: {
    key: 'communicationPreferenceEmail',
    label: 'communicationPreferenceEmail',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  communicationPreferencePhone: {
    key: 'communicationPreferencePhone',
    label: 'communicationPreferencePhone',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  communicationPreferenceSMS: {
    key: 'communicationPreferenceSMS',
    label: 'communicationPreferenceSMS',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  additionalContactDetails: {
    key: 'additionalContactDetails',
    label: 'additionalContactDetails',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  metadata: {
    key: 'metadata',
    label: 'metadata',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  _eTag: {
    key: '_eTag',
    label: '_eTag',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  extrasField: {
    key: 'extrasField',
    label: 'extrasField',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  relationships: {
    key: 'relationships',
    label: 'relationships',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
}
