import { ContextInput, ModelConfig } from '@/components/ModelRuntimeConfig'
import { CreateTenancyModel } from '@/schemas/createTenancyModel.generated.tsx'

export const createTenancyModelConfig: ModelConfig<CreateTenancyModel> = {
  startDate: {
    key: 'startDate',
    label: 'startDate',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  endDate: {
    key: 'endDate',
    label: 'endDate',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  status: {
    key: 'status',
    label: 'status',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  agentRole: {
    key: 'agentRole',
    label: 'agentRole',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  rent: {
    key: 'rent',
    label: 'rent',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  rentFrequency: {
    key: 'rentFrequency',
    label: 'rentFrequency',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  rentInstalmentsFrequency: {
    key: 'rentInstalmentsFrequency',
    label: 'rentInstalmentsFrequency',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  rentInstalmentsAmount: {
    key: 'rentInstalmentsAmount',
    label: 'rentInstalmentsAmount',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  rentInstalmentsStart: {
    key: 'rentInstalmentsStart',
    label: 'rentInstalmentsStart',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  meterReadingGas: {
    key: 'meterReadingGas',
    label: 'meterReadingGas',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  meterReadingGasLastRead: {
    key: 'meterReadingGasLastRead',
    label: 'meterReadingGasLastRead',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  meterReadingElectricity: {
    key: 'meterReadingElectricity',
    label: 'meterReadingElectricity',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  meterReadingElectricityLastRead: {
    key: 'meterReadingElectricityLastRead',
    label: 'meterReadingElectricityLastRead',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  meterReadingWater: {
    key: 'meterReadingWater',
    label: 'meterReadingWater',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  meterReadingWaterLastRead: {
    key: 'meterReadingWaterLastRead',
    label: 'meterReadingWaterLastRead',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  isPeriodic: {
    key: 'isPeriodic',
    label: 'isPeriodic',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  typeId: {
    key: 'typeId',
    label: 'typeId',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  negotiatorId: {
    key: 'negotiatorId',
    label: 'negotiatorId',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  propertyId: {
    key: 'propertyId',
    label: 'propertyId',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  applicantId: {
    key: 'applicantId',
    label: 'applicantId',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  feeNotes: {
    key: 'feeNotes',
    label: 'feeNotes',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  lettingFee: {
    key: 'lettingFee',
    label: 'lettingFee',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  managementFee: {
    key: 'managementFee',
    label: 'managementFee',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  deposit: {
    key: 'deposit',
    label: 'deposit',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  source: {
    key: 'source',
    label: 'source',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  metadata: {
    key: 'metadata',
    label: 'metadata',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
}
