import { ContextInput, ModelConfig } from '@/components/ModelRuntimeConfig'
import { CreateContactModel } from '@/schemas/createContactModel.generated.tsx'

export const createContactModelConfig: ModelConfig<CreateContactModel> = {
  title: {
    key: 'title',
    label: 'title',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  forename: {
    key: 'forename',
    label: 'forename',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  surname: {
    key: 'surname',
    label: 'surname',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  dateOfBirth: {
    key: 'dateOfBirth',
    label: 'dateOfBirth',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  active: {
    key: 'active',
    label: 'active',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  marketingConsent: {
    key: 'marketingConsent',
    label: 'marketingConsent',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  source: {
    key: 'source',
    label: 'source',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  homePhone: {
    key: 'homePhone',
    label: 'homePhone',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  workPhone: {
    key: 'workPhone',
    label: 'workPhone',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  mobilePhone: {
    key: 'mobilePhone',
    label: 'mobilePhone',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  email: {
    key: 'email',
    label: 'email',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  officeIds: {
    key: 'officeIds',
    label: 'officeIds',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  negotiatorIds: {
    key: 'negotiatorIds',
    label: 'negotiatorIds',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  categoryIds: {
    key: 'categoryIds',
    label: 'categoryIds',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  primaryAddress: {
    key: 'primaryAddress',
    label: 'primaryAddress',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  secondaryAddress: {
    key: 'secondaryAddress',
    label: 'secondaryAddress',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  workAddress: {
    key: 'workAddress',
    label: 'workAddress',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  communicationPreferenceLetter: {
    key: 'communicationPreferenceLetter',
    label: 'communicationPreferenceLetter',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  communicationPreferenceEmail: {
    key: 'communicationPreferenceEmail',
    label: 'communicationPreferenceEmail',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  communicationPreferencePhone: {
    key: 'communicationPreferencePhone',
    label: 'communicationPreferencePhone',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  communicationPreferenceSMS: {
    key: 'communicationPreferenceSMS',
    label: 'communicationPreferenceSMS',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  metadata: {
    key: 'metadata',
    label: 'metadata',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
}
