import { ContextInput, ModelConfig } from '@/components/ModelRuntimeConfig'
import { DepartmentModel } from '@/schemas/departmentModel.generated.tsx'

export const departmentModelConfig: ModelConfig<DepartmentModel> = {
  _links: {
    key: '_links',
    label: '_links',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  _embedded: {
    key: '_embedded',
    label: '_embedded',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  id: {
    key: 'id',
    label: 'id',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  created: {
    key: 'created',
    label: 'created',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  modified: {
    key: 'modified',
    label: 'modified',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  name: {
    key: 'name',
    label: 'name',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  typeOptions: {
    key: 'typeOptions',
    label: 'typeOptions',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  styleOptions: {
    key: 'styleOptions',
    label: 'styleOptions',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  situationOptions: {
    key: 'situationOptions',
    label: 'situationOptions',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  parkingOptions: {
    key: 'parkingOptions',
    label: 'parkingOptions',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  ageOptions: {
    key: 'ageOptions',
    label: 'ageOptions',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  localityOptions: {
    key: 'localityOptions',
    label: 'localityOptions',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  specialFeaturesOptions: {
    key: 'specialFeaturesOptions',
    label: 'specialFeaturesOptions',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  commercialUseClassOptions: {
    key: 'commercialUseClassOptions',
    label: 'commercialUseClassOptions',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  commercialFloorLevelOptions: {
    key: 'commercialFloorLevelOptions',
    label: 'commercialFloorLevelOptions',
    defaultValue: [],
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  hasBedrooms: {
    key: 'hasBedrooms',
    label: 'hasBedrooms',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  hasBathrooms: {
    key: 'hasBathrooms',
    label: 'hasBathrooms',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  hasReceptionRooms: {
    key: 'hasReceptionRooms',
    label: 'hasReceptionRooms',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  hasParkingSpaces: {
    key: 'hasParkingSpaces',
    label: 'hasParkingSpaces',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  hasFloorLevelEnabled: {
    key: 'hasFloorLevelEnabled',
    label: 'hasFloorLevelEnabled',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  hasInternalFloorsEnabled: {
    key: 'hasInternalFloorsEnabled',
    label: 'hasInternalFloorsEnabled',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  hasTotalFloorsEnabled: {
    key: 'hasTotalFloorsEnabled',
    label: 'hasTotalFloorsEnabled',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
  _eTag: {
    key: '_eTag',
    label: '_eTag',
    defaultValue: '',
    format: (value) => `${value}`,
    Input: (props) => <ContextInput {...props} />,
  },
}
