import { default as Input } from '@mui/joy/Input'
import { ModelConfig } from '@/components/ModelRuntimeConfig'
import { TenancyModel } from '@/schemas/index.ts'

export const tenancyModelConfig: ModelConfig<TenancyModel> = {
  _links: {
    key: '_links',
    label: '_links',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  _embedded: {
    key: '_embedded',
    label: '_embedded',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  id: {
    key: 'id',
    label: 'id',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  created: {
    key: 'created',
    label: 'created',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  modified: {
    key: 'modified',
    label: 'modified',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  startDate: {
    key: 'startDate',
    label: 'startDate',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  endDate: {
    key: 'endDate',
    label: 'endDate',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  status: {
    key: 'status',
    label: 'status',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  agentRole: {
    key: 'agentRole',
    label: 'agentRole',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  rent: {
    key: 'rent',
    label: 'rent',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  rentFrequency: {
    key: 'rentFrequency',
    label: 'rentFrequency',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  endDateConfirmed: {
    key: 'endDateConfirmed',
    label: 'endDateConfirmed',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  isPeriodic: {
    key: 'isPeriodic',
    label: 'isPeriodic',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  rentInstalmentsFrequency: {
    key: 'rentInstalmentsFrequency',
    label: 'rentInstalmentsFrequency',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  rentInstalmentsAmount: {
    key: 'rentInstalmentsAmount',
    label: 'rentInstalmentsAmount',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  rentInstalmentsStart: {
    key: 'rentInstalmentsStart',
    label: 'rentInstalmentsStart',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  meterReadingGas: {
    key: 'meterReadingGas',
    label: 'meterReadingGas',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  meterReadingGasLastRead: {
    key: 'meterReadingGasLastRead',
    label: 'meterReadingGasLastRead',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  meterReadingElectricity: {
    key: 'meterReadingElectricity',
    label: 'meterReadingElectricity',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  meterReadingElectricityLastRead: {
    key: 'meterReadingElectricityLastRead',
    label: 'meterReadingElectricityLastRead',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  meterReadingWater: {
    key: 'meterReadingWater',
    label: 'meterReadingWater',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  meterReadingWaterLastRead: {
    key: 'meterReadingWaterLastRead',
    label: 'meterReadingWaterLastRead',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  typeId: {
    key: 'typeId',
    label: 'typeId',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  negotiatorId: {
    key: 'negotiatorId',
    label: 'negotiatorId',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  propertyId: {
    key: 'propertyId',
    label: 'propertyId',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  applicantId: {
    key: 'applicantId',
    label: 'applicantId',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  managerId: {
    key: 'managerId',
    label: 'managerId',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  groupPaymentReference: {
    key: 'groupPaymentReference',
    label: 'groupPaymentReference',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  lettingFee: {
    key: 'lettingFee',
    label: 'lettingFee',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  managementFee: {
    key: 'managementFee',
    label: 'managementFee',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  source: {
    key: 'source',
    label: 'source',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  deposit: {
    key: 'deposit',
    label: 'deposit',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  related: {
    key: 'related',
    label: 'related',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  fromArchive: {
    key: 'fromArchive',
    label: 'fromArchive',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  metadata: {
    key: 'metadata',
    label: 'metadata',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  feeNotes: {
    key: 'feeNotes',
    label: 'feeNotes',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  legalStatusId: {
    key: 'legalStatusId',
    label: 'legalStatusId',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  renewalOptions: {
    key: 'renewalOptions',
    label: 'renewalOptions',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  arrears: {
    key: 'arrears',
    label: 'arrears',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
  _eTag: {
    key: '_eTag',
    label: '_eTag',
    format: (value) => `${value}`,
    Input: (props) => <Input {...props} />,
  },
}
