import { z } from 'zod'
import { linkModel, LinkModel } from '@/schemas/linkModel.generated.tsx'
import { enquiryAddressModel, EnquiryAddressModel } from '@/schemas/enquiryAddressModel.generated.tsx'
import { enquiryBuyingModel, EnquiryBuyingModel } from '@/schemas/enquiryBuyingModel.generated.tsx'
import { enquiryRentingModel, EnquiryRentingModel } from '@/schemas/enquiryRentingModel.generated.tsx'

/** Representation of an enquiry */
export const enquiryModel =
  /** Representation of an enquiry */
  z.object({
    _links: z.record(z.string(), linkModel).optional(),
    _embedded: z.record(z.string(), z.object({})).optional(),
    /** The unique identifier of the enquiry */ id: z.number().int().optional(),
    /** The date and time when the enquiry was created */ created: z.string().optional(),
    /** The date and time when the enquiry was last modified */ modified: z.string().optional(),
    /** The title of the individual making the enquiry */ title: z.string().optional(),
    /** The forename of the individual making the enquiry */ forename: z.string().optional(),
    /** The surname of the individual making the enquiry */ surname: z.string().optional(),
    /** The type of enquiry. Enquiries can created for applicants interested in buying/renting, as well as prospective vendors and landlords (salesApplicant/lettingsApplicant/salesProperty/lettingsProperty) */
    enquiryType: z.string().optional(),
    /** Textual information about the nature of the enquiry - usually the message text from the individual making the enquiry */
    message: z.string().optional(),
    /** The status of the enquiry (pending/added/rejected/alreadyExists/duplicateEntry/spam) */
    status: z.string().optional(),
    /** The marketing consent status of the individual making the enquiry (grant/deny/notAsked) */
    marketingConsent: z.string().optional(),
    /** The selling position of the individual making the enquiry (renting/instructedThisAgent/instructedOtherAgent/privateSale/notOnMarket) */
    position: z.string().optional(),
    /** The unique identifier of the office related to the enquiry */ officeId: z.string().optional(),
    /** The unique identifier of the applicant related to the enquiry */ applicantId: z.string().optional(),
    /** The unique identifier of the negotiator related to the enquiry */ negotiatorId: z.string().optional(),
    /** The name of the source that the enquiry was generated by */ sourceName: z.string().optional(),
    /** The home phone number of the individual making the enquiry */ homePhone: z.string().optional(),
    /** The work phone number of the individual making the enquiry */ workPhone: z.string().optional(),
    /** The mobile phone number of the individual making the enquiry */ mobilePhone: z.string().optional(),
    /** The email of the individual making the enquiry */ email: z.string().optional(),
    address: enquiryAddressModel.optional(),
    buying: enquiryBuyingModel.optional(),
    renting: enquiryRentingModel.optional(),
    /** The number of bedrooms the prospective buyer or tenant requires */ bedrooms: z.number().int().optional(),
    /** A list of unique property identifiers that this enquiry relates to. Used to indicate the properties that a sales or lettings applicant has expressed an interest in */
    propertyIds: z.array(z.string()).optional(),
    /** The ETag for the current version of the enquiry. Used for managing update concurrency */
    _eTag: z.string().optional(),
  })
/** Representation of an enquiry */
export type EnquiryModel =
  /** Representation of an enquiry */
  {
    _links?: Record<string, LinkModel> | undefined
    _embedded?: Record<string, Record<string, never>> | undefined
    id?: /** The unique identifier of the enquiry */ number | undefined
    created?: /** The date and time when the enquiry was created */ string | undefined
    modified?: /** The date and time when the enquiry was last modified */ string | undefined
    title?: /** The title of the individual making the enquiry */ string | undefined
    forename?: /** The forename of the individual making the enquiry */ string | undefined
    surname?: /** The surname of the individual making the enquiry */ string | undefined
    enquiryType?: /** The type of enquiry. Enquiries can created for applicants interested in buying/renting, as well as prospective vendors and landlords (salesApplicant/lettingsApplicant/salesProperty/lettingsProperty) */
    string | undefined
    message?: /** Textual information about the nature of the enquiry - usually the message text from the individual making the enquiry */
    string | undefined
    status?: /** The status of the enquiry (pending/added/rejected/alreadyExists/duplicateEntry/spam) */
    string | undefined
    marketingConsent?: /** The marketing consent status of the individual making the enquiry (grant/deny/notAsked) */
    string | undefined
    position?: /** The selling position of the individual making the enquiry (renting/instructedThisAgent/instructedOtherAgent/privateSale/notOnMarket) */
    string | undefined
    officeId?: /** The unique identifier of the office related to the enquiry */ string | undefined
    applicantId?: /** The unique identifier of the applicant related to the enquiry */ string | undefined
    negotiatorId?: /** The unique identifier of the negotiator related to the enquiry */ string | undefined
    sourceName?: /** The name of the source that the enquiry was generated by */ string | undefined
    homePhone?: /** The home phone number of the individual making the enquiry */ string | undefined
    workPhone?: /** The work phone number of the individual making the enquiry */ string | undefined
    mobilePhone?: /** The mobile phone number of the individual making the enquiry */ string | undefined
    email?: /** The email of the individual making the enquiry */ string | undefined
    address?: EnquiryAddressModel | undefined
    buying?: EnquiryBuyingModel | undefined
    renting?: EnquiryRentingModel | undefined
    bedrooms?: /** The number of bedrooms the prospective buyer or tenant requires */ number | undefined
    propertyIds?: /** A list of unique property identifiers that this enquiry relates to. Used to indicate the properties that a sales or lettings applicant has expressed an interest in */
    Array<string> | undefined
    _eTag?: /** The ETag for the current version of the enquiry. Used for managing update concurrency */
    string | undefined
  }
