import { z } from 'zod'

/** Representation of an enquiry */
export const enquiryModel = z.object({
  _links: z
    .record(z.string(), z.object({ href: z.string().nullable().optional() }))
    .nullable()
    .optional(),
  _embedded: z.record(z.string(), z.object({})).nullable().optional(),
  /** The unique identifier of the enquiry */ id: z.number().int().nullable().optional(),
  /** The date and time when the enquiry was created */ created: z.string().nullable().optional(),
  /** The date and time when the enquiry was last modified */ modified: z.string().nullable().optional(),
  /** The title of the individual making the enquiry */ title: z.string().nullable().optional(),
  /** The forename of the individual making the enquiry */ forename: z.string().nullable().optional(),
  /** The surname of the individual making the enquiry */ surname: z.string().nullable().optional(),
  /** The type of enquiry. Enquiries can created for applicants interested in buying/renting, as well as prospective vendors and landlords (salesApplicant/lettingsApplicant/salesProperty/lettingsProperty) */
  enquiryType: z.string().nullable().optional(),
  /** Textual information about the nature of the enquiry - usually the message text from the individual making the enquiry */
  message: z.string().nullable().optional(),
  /** The status of the enquiry (pending/added/rejected/alreadyExists/duplicateEntry/spam) */
  status: z.string().nullable().optional(),
  /** The marketing consent status of the individual making the enquiry (grant/deny/notAsked) */
  marketingConsent: z.string().nullable().optional(),
  /** The selling position of the individual making the enquiry (renting/instructedThisAgent/instructedOtherAgent/privateSale/notOnMarket) */
  position: z.string().nullable().optional(),
  /** The unique identifier of the office related to the enquiry */ officeId: z.string().nullable().optional(),
  /** The unique identifier of the applicant related to the enquiry */ applicantId: z.string().nullable().optional(),
  /** The unique identifier of the negotiator related to the enquiry */ negotiatorId: z.string().nullable().optional(),
  /** The name of the source that the enquiry was generated by */ sourceName: z.string().nullable().optional(),
  /** The home phone number of the individual making the enquiry */ homePhone: z.string().nullable().optional(),
  /** The work phone number of the individual making the enquiry */ workPhone: z.string().nullable().optional(),
  /** The mobile phone number of the individual making the enquiry */ mobilePhone: z.string().nullable().optional(),
  /** The email of the individual making the enquiry */ email: z.string().nullable().optional(),
  /** Representation of the physical address of a building or premise */
  address: z
    .object({
      /** The building name */ buildingName: z.string().nullable().optional(),
      /** The building number */ buildingNumber: z.string().nullable().optional(),
      /** The first line of the address */ line1: z.string().nullable().optional(),
      /** The second line of the address */ line2: z.string().nullable().optional(),
      /** The third line of the address */ line3: z.string().nullable().optional(),
      /** The fourth line of the address */ line4: z.string().nullable().optional(),
      /** The postcode */ postcode: z.string().nullable().optional(),
      /** The ISO-3166 country code that the address resides within */ countryId: z.string().nullable().optional(),
    })
    .nullable()
    .optional(),
  /** Request body used to create a buying enquiry */
  buying: z
    .object({
      /** The lower bound of the prospective buyer's budget */ priceFrom: z.number().int().nullable().optional(),
      /** The upper bound of the prospective buyer's budget */ priceTo: z.number().int().nullable().optional(),
    })
    .nullable()
    .optional(),
  /** The details specific to enquiries with a type of lettingsApplicant */
  renting: z
    .object({
      /** The lower bound of the prospective tenant's budget */ rentFrom: z.number().nullable().optional(),
      /** The upper bound of the prospective tenant's budget */ rentTo: z.number().nullable().optional(),
      /** How often the tenant would like to pay the rent (weekly/monthly/annually) */
      rentFrequency: z.string().nullable().optional(),
    })
    .nullable()
    .optional(),
  /** The number of bedrooms the prospective buyer or tenant requires */
  bedrooms: z.number().int().nullable().optional(),
  /** A list of unique property identifiers that this enquiry relates to. Used to indicate the properties that a sales or lettings applicant has expressed an interest in */
  propertyIds: z.array(z.string()).nullable().optional(),
  /** The ETag for the current version of the enquiry. Used for managing update concurrency */
  _eTag: z.string().nullable().optional(),
})
